setlocal cindent
setlocal cinoptions=l1,g0
setlocal expandtab
setlocal formatoptions-=c
setlocal formatoptions-=o
setlocal formatoptions-=q
setlocal formatoptions-=r
setlocal shiftwidth=2
setlocal softtabstop=2
setlocal tabstop=2
