setlocal cindent
setlocal cinoptions=:0,l1,g0
setlocal expandtab
setlocal formatoptions-=c
setlocal formatoptions-=o
setlocal formatoptions-=r
setlocal makeprg=build
setlocal shiftwidth=3
setlocal softtabstop=3
setlocal tabstop=3
