setlocal cindent
setlocal cinoptions+=:2
setlocal cinoptions+==2
setlocal cinoptions+=E-s
setlocal cinoptions+=N-s
setlocal cinoptions+=g1
setlocal cinoptions+=h1
setlocal cinoptions+=j1
setlocal cinoptions+=l1
setlocal cinoptions+=t0
setlocal foldmethod=marker
setlocal formatoptions+=j
setlocal textwidth=100
