" Enable filetype support, supporting filetype-specific indentation, syntax
" highlighting and other goodies.
filetype plugin indent on

" Enable syntax highlighting, overriding current color settings with defaults.
set background=dark
color torte
syntax on

set autoread
set backspace=indent,eol,start
set completeopt=
set encoding=utf-8
set fileformats=unix,dos,mac
set hidden
set hlsearch
set ignorecase
set incsearch
set listchars=tab:‣\ ,space:·
set mouse=a
set nojoinspaces
set ruler
set shortmess+=I
set splitbelow
set splitright

if has('win32')
    set guicursor=a:block-Cursor
endif

set autoindent
set copyindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=8

let c_no_curly_error = 1

let &grepprg = 'grep -RIn $* .'
let g:mapleader = ' '
let g:maplocalleader = "\\"
let g:omni_sql_no_default_maps = 1

nnoremap N Nzz
nnoremap n nzz

nnoremap <Leader><Leader> <Cmd>nohlsearch<CR>
nnoremap <Leader>P "+P
nnoremap <Leader>e <Cmd>edit $MYVIMRC<CR>
nnoremap <Leader>f :silent grep<Space>
nnoremap <Leader>g :silent grep <C-R><C-W><CR>
nnoremap <Leader>p "+p
nnoremap <Leader>q <Cmd>setlocal list!<CR>
nnoremap <Leader>y "+y
nnoremap <Leader>yy "+yy
nnoremap <Leader>z <Cmd>setlocal spell!<CR>
nnoremap [q <Cmd>cprev<CR>zz
nnoremap ]q <Cmd>cnext<CR>zz

vnoremap <Leader>p "+p
vnoremap <Leader>s :sort<CR>
vnoremap <Leader>y "+y

" Jump to the last known cursor position in a buffer. Taken from Vim's `defaults.vim`:
" https://github.com/vim/vim/blob/e978b4534a5e10471108259118c0ef791106fd92/runtime/defaults.vim#L111
function! s:RestoreCursorPosition()
    let line = line("'\"")
    if line >= 1 && line <= line('$') && &filetype !~# 'commit'
    \ && index(['xxd', 'gitrebase'], &filetype) == -1
        execute 'normal! g`"'
        execute 'normal! zz'
    endif
endfunction

augroup restore_cursor_position
    autocmd!
    autocmd BufReadPost * call s:RestoreCursorPosition()
augroup END

augroup misc
    autocmd QuickFixCmdPost [^l]* cwindow | redraw
augroup END
