" Enable filetype support, supporting filetype-specific indentation, syntax
" highlighting and other goodies.
filetype plugin indent on

" Enable syntax highlighting, overriding current color settings with defaults.
syntax on

set autoindent
set autoread
set backspace=indent,eol,start
set completeopt=
set encoding=utf-8
set fileformats=unix,dos,mac
set hidden
set ignorecase
set incsearch
set laststatus=2
set lazyredraw
set listchars=tab:→\ ,space:·
set nojoinspaces
set ruler
set scrolloff=8
set shortmess+=I
set sidescrolloff=8
set smartcase
set splitbelow
set splitright
set virtualedit=all

set expandtab
set shiftwidth=4
set tabstop=4
set textwidth=80

if has('gui_running')
    set guioptions-=m
    set guioptions-=T
    set guioptions-=L
    set guioptions-=r

    set renderoptions=type:directx,renmode:5,taamode:1
    if has('win32')
        set guifont=DejaVu_Sans_Mono:h10
    else
        set guifont=DejaVu\ Sans\ Mono\ 10
    endif
elseif has('win32')
    set termguicolors
endif

colorscheme torte
highlight ExtraWhitespace guibg=red
highlight LongLine gui=underline term=underline
highlight Normal guibg=#1c1c1c
" @todo: I don't think this match is executing properly.
match ExtraWhitespace /\s\+$/
match LongLine '\%>80v.\+'

let g:mapleader = ' '

" Make <Esc> exit insert mode in vertical block mode.
inoremap <C-C> <Esc>

nnoremap <C-D> <C-D>zz
nnoremap <C-U> <C-U>zz
nnoremap <Leader>p "*p
nnoremap <Leader>q <Cmd>set list!<CR>
nnoremap <Leader>y "*y
nnoremap N Nzz
nnoremap j gj
nnoremap k gk
nnoremap n nzz

vnoremap <F2> d:execute 'normal i' . join(sort(split(getreg('"'))), ' ')<CR>
vnoremap <Leader>p "*p
vnoremap <Leader>s :sort<CR>
vnoremap <Leader>y "*y
